/*
집계함수: 데이터를 그룹화해준다.
GROUP BY: 그룹화의 기준
HAVING: 집계함수에 대해 조건을 제한하기 위함
ROLLUP: 총합 또는 중간 합계
*/
-- GROUP BY는 그룹화의 기준이다.
SELECT	USERID, SUM(PRICE * AMOUNT)
FROM		BUYTBL
GROUP BY	USERID

-- 가장 큰 키와 가장 작은 키를 찾고자 할 때
SELECT	USERNAME, HEIGHT
FROM		USERTBL
WHERE HEIGHT = (SELECT MAX(HEIGHT) FROM USERTBL)
OR	HEIGHT = (SELECT MIN(HEIGHT) FROM USERTBL)

-- 휴대폰이 있는 사용자 수
SELECT	COUNT(MOBILE1)
FROM		USERTBL

-- 총 구매액이 1000 이상
SELECT	USERID, SUM(PRICE * AMOUNT)
FROM		BUYTBL
GROUP BY USERID
HAVING SUM(PRICE * AMOUNT) >= 1000

-- ROLL UP
-- ROLLUP을 활용할 때 GROUP BY의 순서를 고려해야됨. 만약 NUM, GROUPNAME이었으면 다른 결과가 나옴
-- GROUP BY NUM, GROUPNAME -> NUM순서에 따라(= NUM 별로) 합계 및 총합 결과 산출
-- GROUP BY GROUPNAME, NUM -> GROUPNAME별로 합계 및 총합 결과 산출
SELECT	NUM, GROUPNAME, SUM(PRICE * AMOUNT)
FROM		BUYTBL
GROUP BY GROUPNAME, NUM
WITH ROLLUP;

